### ISSUE TITLE
More guidance on script naming / placement?

### ISSUE THREAD

**Issue by rcavalcante** [umich-brcf-bioinf/2022-03-14-umich-rnaseq-demystified#12]
https://github.com/umich-brcf-bioinf/2022-03-14-umich-rnaseq-demystified/blob/3ff3e9d034d386acb5b1371019075c5e7dac1183/source/Module06_DEAnalysisSetup.Rmd#L74-L82

Not sure if there was going to be a spoken recommendation to put in `~/RSD_R`? A written suggestion might be helpful for when people go back and look at this outside of the workshop.

**Comment by dkcoxie** [comment]
We will be creating directories before we save the file but clarified checkpoint language to indicate file is unsaved at this stage.
