### ISSUE TITLE
Fix bullet formatting in <details>

### ISSUE THREAD

**Issue by rcavalcante** [umich-brcf-bioinf/2022-03-14-umich-rnaseq-demystified#13]
https://github.com/umich-brcf-bioinf/2022-03-14-umich-rnaseq-demystified/blob/3ff3e9d034d386acb5b1371019075c5e7dac1183/source/Module06_DEAnalysisSetup.Rmd#L134-L142

For the bullets to work in the `<details>` tag, there needs to be an extra space above the first bullet.

**Comment by dkcoxie** [comment]
Ah! Thank you.
