### ISSUE TITLE
Consider altering indentation

### ISSUE THREAD

**Issue by rcavalcante** [umich-brcf-bioinf/2022-03-14-umich-rnaseq-demystified#14]
https://github.com/umich-brcf-bioinf/2022-03-14-umich-rnaseq-demystified/blob/3ff3e9d034d386acb5b1371019075c5e7dac1183/source/Module07_DESeq2Init.Rmd#L119-L125

When knitted, the wrap is unfortunate, consider:
```
MetaInfo$Gtype.Tx <- factor(MetaInfo$Gtype.Tx, 
                            levels = c( "wt.Tx", "ko.Tx", "ko.control", "wt.control" ))
```

**Comment by dkcoxie** [comment]
Modified line indentation as suggested
