### ISSUE TITLE
Code block issue in <details>

### ISSUE THREAD

**Issue by rcavalcante** [umich-brcf-bioinf/2022-03-14-umich-rnaseq-demystified#15]
https://github.com/umich-brcf-bioinf/2022-03-14-umich-rnaseq-demystified/blob/3ff3e9d034d386acb5b1371019075c5e7dac1183/source/Module08_DESeq2DE.Rmd#L125-L134

I think the code blocks also need to have an empty line above them for them to render properly in the hidden block.

**Comment by dkcoxie** [comment]
Fixed indentation so code block is now formatted.
